### ISSUE TITLE
Write announcement for TonDevNews

### ISSUE THREAD

**Issue by anton-trunov** [tact-lang/tact-sublime#12]
- [ ] an animated gif showcasing the plugin
- [ ] short text about the most interesting features
- [ ] link to this repo
- [ ] how to install it
- [ ] author credit

**Comment by novusnota** [comment]
Depends on #5, as I'd like to make such an announcement when the best installation option (in terms of UX) comes available for users :)

**Comment by anton-trunov** [comment]
I mean, writing an announcement can be done before, it's publishing the announcement actually depends on #5 :)

**Comment by novusnota** [comment]
Will do it tomorrow, as package is just published: https://packagecontrol.io/packages/Tact

**Comment by novusnota** [comment]
@anton-trunov 

Went with .webm this time, Telegram supports it well:

[preview video](https://github.com/tact-lang/tact-sublime/assets/68142933/45c91a2c-05ca-4762-95db-ebf5fbe77f22)

---

**The new Sublime Text 4 package for Tact is now available.**

🚀 We're thrilled to announce the launch of a new official ST4 package for the Tact language! Check it out to enhance your coding experience: [tact-sublime](https://github.com/tact-lang/tact-sublime).

✨ Features:

• Syntax highlighting
• Auto-completions and code snippets
• Syntax checks through simple Tact compiler integration
• Symbol lists, indentation, folding and comments
• ...for all the details, see its [README](https://github.com/tact-lang/tact-sublime/blob/main/README.md)

⚙️ Installation:

1. Open the command palette with _Ctrl + Shift + P_ (or _Cmd + Shift + P_ on macOS)
2. Select **Package Control: Install Package** (install [Package Control](https://packagecontrol.io/installation), if it's missing)
3. Type and select **Tact**

👨‍💻 Made with 🤍 by [Novus Nota](https://github.com/novusnota)
⚡️ Happy coding with Tact!
👨‍🍳 And also come visit whats [cooking there](https://t.me/tact_kitchen) 🤌

**Comment by anton-trunov** [comment]
Published here: https://t.me/tondev_news/120
